apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: newdiscapi
  namespace: 'PROJECT_ID'
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/ingress: all
    spec:
      containerConcurrency: 80
      containers:
        - image: gcr.io/PROJECT_ID/newdiscapi
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: API_KEY
              value: 'replace_me'
            - name: ALLOWED_ORIGINS
              value: 'https://example.com'
            - name: FIREBASE_PROJECT_ID
              value: 'ouzaz-ac5bd'
            # Option 1: Inline JSON credentials (less secure, visible in YAML)
            # - name: FIREBASE_CREDENTIALS_JSON
            #   value: '{"type":"service_account","project_id":"your-project",...}'
            
            # Option 2: Use Application Default Credentials (recommended)
            # Set GOOGLE_APPLICATION_CREDENTIALS to use service account attached to Cloud Run
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: 'service-account.json'
            
            # Option 3: Use Secret Manager (most secure)
            # - name: FIREBASE_CREDENTIALS_JSON
            #   valueFrom:
            #     secretKeyRef:
            #       name: firebase-credentials
            #       key: service-account-json

